---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: allomov/deploy-worker
    tag: "v2.0"

run:
  path: pipeline-repo/ci/scripts/deploy.sh
  
inputs:
- name: pipeline-repo
  
