resources:
- name: pipeline-repo
  type: git
  check: 2m
  source:
    uri: https://github.com/Altoros/concourse-deploy-turbulence.git

jobs:
- name: deploy-turbulence
  plan:
  - aggregate:
    - get: pipeline-repo
  - task: deploy-turbulence
    file: pipeline-repo/ci/tasks/deploy.yml

- name: kill-turbulence
  plan:
  - aggregate:
    - get: pipeline-repo
  - taks: kill-turbulence
    file: pipeline-repo/ci/tasks/kill.yml
