resources:
- name: pipeline-repo
  type: git
  check: 2m
  source:
    uri: {{pipeline-repo}}
    branch: {{pipeline-repo-branch}}
    private_key: {{pipeline-repo-private-key}}

jobs:
- name: deploy-turbulence
  plan:
  - get: pipeline-repo
  - task: deploy-turbulence
    file: pipeline-repo/ci/tasks/deploy.yml
    params:
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}

- name: kill-turbulence
  plan:
  - get: pipeline-repo
  - task: kill-turbulence
    file: pipeline-repo/ci/tasks/kill.yml
    params:
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}

